import { StructuredPacket } from '../structuring/structurePacket';

/**
 * Render a StructuredPacket as a markdown string.
 */
export function renderMarkdown(packet: StructuredPacket): string {
  const lines: string[] = [];

  lines.push(`# Packet: ${packet.sourceName}`);
  lines.push('');
  lines.push(`_Generated by Packetor_`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(packet.summary);
  lines.push('');

  // Key Facts
  lines.push('## Key Facts');
  lines.push('');
  if (packet.facts.length > 0) {
    for (const fact of packet.facts) {
      lines.push(`- **${fact.label}**: ${fact.value}`);
    }
  } else {
    lines.push('_No key facts extracted._');
  }
  lines.push('');

  // Timeline
  lines.push('## Timeline');
  lines.push('');
  if (packet.timeline.length > 0) {
    for (const entry of packet.timeline) {
      lines.push(`- **${entry.date}** — ${entry.event}`);
    }
  } else {
    lines.push('_No timeline entries found._');
  }
  lines.push('');

  // Risk Flags
  if (packet.riskFlags.length > 0) {
    lines.push('## Risk Flags');
    lines.push('');
    for (const flag of packet.riskFlags) {
      lines.push(`- ⚠️ ${flag}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`_Source: ${packet.sourceName}_`);

  return lines.join('\n');
}
